RootDir = '~/chainlink'
[Log]
Level = 'warn'

[WebServer]
AllowOrigins = '\*'
SecureCookies = false

[WebServer.TLS]
HTTPSPort = 0

[[EVM]]
ChainID = '11155111'

[[EVM.Nodes]]
Name = 'Sepolia'
WSURL = 'wss://ethereum-sepolia-rpc.publicnode.com'
HTTPURL = 'https://1rpc.io/sepolia'